# Generated by Django 3.2.7 on 2021-09-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210917_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidades',
            name='habilidad',
            field=models.CharField(max_length=50, unique=True, verbose_name='Habilidad'),
        ),
    ]
