# Generated by Django 3.2.7 on 2021-09-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_empleado_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='full_name',
        ),
    ]
